---

sidecar:
  name: "us.gcr.io/lucidworks-helm-fusion/hpa-metrics"
  tag: "latest"

# Which port should solr listen on
port: 8983

# Number of solr instances to run
replicaCount: 3

# Settings for solr java memory
javaMem: "-Xms2g -Xmx3g"

# Set the limits and requests on solr pod resources
resources: {}

# Sets the termination Grace period for the solr pods
# This can take a while for shards to elect new leaders
terminationGracePeriodSeconds: 180

# Solr image settings
image:
  repository: solr
  tag: 7.6.0
  pullPolicy: Always

# Solr pod liveness
livenessProbe:
  initialDelaySeconds: 20
  periodSeconds: 10

# Solr pod readiness
readinessProbe:
  initialDelaySeconds: 15
  periodSeconds: 5

# Annotations to apply to the solr pods
podAnnotations:
  ad.datadoghq.com/solr.check_names: |
    [
      "solr"
    ]
  ad.datadoghq.com/solr.init_configs: |
    [
      {
              "is_jmx": true,
              "collect_default_metrics": true,
              "conf": [
                  {
                      "include": {
                          "category": "SEARCHER",
                          "name": [
                              "numDocs"
                          ],
                          "scope": [
                              "searcher"
                          ],
                          "attribute": {
                              "Value": {
                                  "alias": "solr.searcher.numdocs",
                                  "metric_type": "gauge"
                              }
                          }
                      }
                  },
                  {
                      "include": {
                          "category": "SEARCHER",
                          "name": "maxDoc",
                          "scope": [
                              "searcher"
                          ],
                          "attribute": {
                              "Value": {
                                  "alias": "solr.searcher.maxdocs",
                                  "metric_type": "gauge"
                              }
                          }
                      }
                  },
                  {
                      "include": {
                          "category": "SEARCHER",
                          "name": "warmupTime",
                          "scope": [
                              "searcher"
                          ],
                          "attribute": {
                              "Value": {
                                  "alias": "solr.searcher.warmup",
                                  "metric_type": "gauge"
                              }
                          }
                      }
                  },
                  {
                      "include": {
                          "category": "CACHE",
                          "name": "documentCache",
                          "scope": [
                              "searcher"
                          ],
                          "attribute": {
                              "cumulative_lookups": {
                                  "alias": "solr.document_cache.lookups",
                                  "metric_type": "counter"
                              },
                              "cumulative_hits": {
                                  "alias": "solr.document_cache.hits",
                                  "metric_type": "counter"
                              },
                              "cumulative_inserts": {
                                  "alias": "solr.document_cache.inserts",
                                  "metric_type": "counter"
                              },
                              "cumulative_evictions": {
                                  "alias": "solr.document_cache.evictions",
                                  "metric_type": "counter"
                              }
                          }
                      }
                  },
                  {
                      "include": {
                          "category": "CACHE",
                          "name": "queryResultCache",
                          "scope": [
                              "searcher"
                          ],
                          "attribute": {
                              "cumulative_lookups": {
                                  "alias": "solr.query_result_cache.lookups",
                                  "metric_type": "counter"
                              },
                              "cumulative_hits": {
                                  "alias": "solr.query_result_cache.hits",
                                  "metric_type": "counter"
                              },
                              "cumulative_inserts": {
                                  "alias": "solr.query_result_cache.inserts",
                                  "metric_type": "counter"
                              },
                              "cumulative_evictions": {
                                  "alias": "solr.query_result_cache.evictions",
                                  "metric_type": "counter"
                              }
                          }
                      }
                  },
                  {
                      "include": {
                          "category": "CACHE",
                          "name": "filterCache",
                          "scope": [
                              "searcher"
                          ],
                          "attribute": {
                              "cumulative_lookups": {
                                  "alias": "solr.filter_cache.lookups",
                                  "metric_type": "counter"
                              },
                              "cumulative_hits": {
                                  "alias": "solr.filter_cache.hits",
                                  "metric_type": "counter"
                              },
                              "cumulative_inserts": {
                                  "alias": "solr.filter_cache.inserts",
                                  "metric_type": "counter"
                              },
                              "cumulative_evictions": {
                                  "alias": "solr.filter_cache.evictions",
                                  "metric_type": "counter"
                              }
                          }
                      }
                  },
                  {
                      "include": {
                          "category": "QUERY",
                          "name": "requests",
                          "attribute": {
                              "Count": {
                                  "alias": "solr.search_handler.requests",
                                  "metric_type": "counter"
                              }
                          }
                      }
                  },
                  {
                      "include": {
                          "category": "QUERY",
                          "name": "timeouts",
                          "attribute": {
                              "Count": {
                                  "alias": "solr.search_handler.timeouts",
                                  "metric_type": "counter"
                              }
                          }
                      }
                  },
                  {
                      "include": {
                          "category": "QUERY",
                          "name": "errors",
                          "attribute": {
                              "Count": {
                                  "alias": "solr.search_handler.errors",
                                  "metric_type": "counter"
                              }
                          }
                      }
                  },
                  {
                      "include": {
                          "category": "QUERY",
                          "name": "totalTime",
                          "attribute": {
                              "Count": {
                                  "alias": "solr.search_handler.time",
                                  "metric_type": "counter"
                              }
                          }
                      }
                  },
                  {
                      "include": {
                          "category": "QUERY",
                          "scope": "/select",
                          "name": "requestTimes",
                          "attribute": {
                              "RateUnit": {
                                  "alias": "solr.search_handler.select_avg_requests_per_sec",
                                  "metric_type": "gauge"
                              },
                              "MeanRate": {
                                  "alias": "solr.search_handler.select_avg_time_per_req",
                                  "metric_type": "gauge"
                              }
                          }
                      }
                  },
                  {
                      "include": {
                          "category": "QUERY",
                          "scope": "/select",
                          "name": "requestTimes",
                          "attribute": {
                              "OneMinuteRate": {
                                  "alias": "solr.search_handler.select_one_minute_rate",
                                  "metric_type": "gauge"
                              }
                          }
                      }
                  }
              ]
      }
    ]
  ad.datadoghq.com/solr.instances: |
    [
      {
        "host": "%%host%%",
        "port": "9999"
      }
    ]

  sidecar.istio.io/inject: "true"

# Node label-values required to run solr pods.
nodeSelector: {}

# Affinity group rules or the solr pods
affinity: {}

# Update Strategy for solr pods
updateStrategy:
  type: "OnDelete"

# The log level of the Solr instances
logLevel: "INFO"

# Solr pod disruption budget
podDisruptionBudget:
  maxUnavailable: 1

# Configuration for the solr PVC
volumeClaimTemplates:
  storageClassName: ""
  storageSize: "20Gi"
  accessModes:
    - "ReadWriteOnce"

# Configuration for solr TLS handling, see README.md for more instructions
tls:
  enabled: false
  wantClientAuth: "false"
  needClientAuth: "false"
  keystorePassword: "changeit"
  importKubernetesCA: "false"
  checkPeerName: "false"
  caSecret:
    name: ""
    bundlePath: ""
  certSecret:
    name: ""
    keyPath: "tls.key"
    certPath: "tls.crt"

# Configuration for the solr service
service:
  type: ClusterIP
  annotations: {}

# Configuration for the solr prometheus exporter
exporter:
  enabled: false # Deploy the exporter
  configFile: "/opt/solr/contrib/prometheus-exporter/conf/solr-exporter-config.xml" # The config file to point the exporter to
  updateStrategy: {}
  podAnnotations: {
    prometheus.io/scrape: "true"
  } # Annotations to apply to the exporter pod
  resources: {} # Resource limits for the exporter
  port: 9983 # The port to run the exporter on
  threads: 7 # The number of threads the exporter uses to query solr
  livenessProbe: # Liveness configuration for exporter pod
    initialDelaySeconds: 20
    periodSeconds: 10
  readinessProbe: # Readiness configuration for exporter pod
    initialDelaySeconds: 15
    periodSeconds: 5
  service:
    type: "ClusterIP"
    annotations: {}
